import "../styles/globals.css";
import Navbar from "./components/Navbar/Navbar";

export const metadata = {
  title: "Givingly",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className="body-text body-bg">
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
