import "styles/globals.css";
import Navbar from "app/[lng]/components/Navbar/Navbar.jsx";
import { ReduxProvider } from "../../app/lib/features/provider";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { Footer } from "./components/Footer";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: "Givingly",
  description: "Generated by create next app",
};

const RootLayout = ({ children, params: { lng } }) => {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className="body-text body-bg">
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer lng={lng}/>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
